### ISSUE TITLE
Compiler can't find Qt5 libraries

### ISSUE THREAD

**Issue by joaocandre** [ros-melodic-arch/ros-melodic-rviz#4] opened 2019-06-22 19:24 UTC
Can't compile currently, some Qt environment flags are not being set correctly:

    g++: error: 0/libQt5Core.so: No such file or directory
    make[3]: *** [Makefile:38: "/home/user/.cache/yay/ros-melodic-rviz/src/build/devel/lib/python3.7/site-
    packages/rviz/librviz_sip".so] Error 1
    make[2]: *** [src/python_bindings/sip/CMakeFiles/librviz_sip.dir/build.make:61: devel/lib/python3.7/site-packages/rviz/librviz_sip.so] Error 2
    make[1]: *** [CMakeFiles/Makefile2:4935: src/python_bindings/sip/CMakeFiles/librviz_sip.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2

I've verified that `pyqt5-common`, `python-pyqt5`, `python-sip-pyqt5` and `qt5-base` are installed. As suggested on the AUR package page, I've tried setting QT_INSTALL_LIBS to `/usr/lib` (where the libs are), but instead I get:

    /bin/sh: /usr/lib: syntax error: operand expected (error token is "/usr/lib")

And if set QT_INSTALL_LIBS=-l/usr/lib/libQt5Core.so, I get instead:

	/bin/sh: -l/usr/lib/libQt5Core.so: division by 0 (error token is "usr/lib/libQt5Core.so")

So is there a workaround for the moment? What environment variable do I need to set?

**Comment by acxz** [comment] 2019-06-24 15:24
Just would like to pipe in that I am also getting the same error, after a clean build of this package and its dependencies.

**Comment by acxz** [comment] 2019-06-25 18:35
Seems like astier on the AUR comments posted the following [solution](https://aur.archlinux.org/packages/ros-melodic-rviz/#comment-698298):
> I fixed the QT_INSTALL_LIBS error by
> 1.    Compile first
> 2.    `sed -i 's/$$\[QT_INSTALL_LIBS\]/\/usr\/lib/' src/build/devel/bin/sip/rviz_sip/Makefile`
> 3.    `makepkg -sie`

**Comment by bionade24** [comment] 2019-06-25 18:44
I'll make an upstream issue, because we can't hardcode the Qt PATH. Maybe we could find the script without Shebang and add `#!/bin/bash`, so that `/bin/sh` doesn't throw the error.

**Comment by bionade24** [comment] 2019-06-26 08:53
https://github.com/ros-visualization/rviz/issues/1382

**Comment by acxz** [comment] 2019-06-27 15:58
I created #5 that has a hacky solution for this. Basically I run the `make` once to let it build, if it errors out apply @astier's solution and then finish the `make` by running it again. Since the compiling itself is done by that point there is not a lot of duplicate overhead, just the relinking after the `sed` command.

I do admit it is dirty, but it fixes the package build. @joaocandre if you could try it on your system as well, that would be great.

**Comment by acxz** [comment] 2019-06-27 16:03
Since #5 got merged is it safe to close this? As of now this issue is just a duplicate of the upstream issue.

**Comment by bionade24** [comment] 2019-06-27 16:05
The issue of the package is now fixed, so only the upstream issue remains.

**Comment by acxz** [comment] 2019-09-29 19:28
Reopening since while not technically a patch, we are using a workaround in the PKGBUILD.

**Comment by bionade24** [comment] 2019-09-29 19:29
Doesn't matter. Thanks for doing this.

**Closed as completed** 2019-10-11 15:54 UTC
Labels: patched
